### ISSUE TITLE
Visually rendering dot-string in React

### ISSUE THREAD

**Issue by its-felix** [ts-graphviz/ts-graphviz#1036]
**Is your feature request related to a problem? Please describe.**
I have server generated .dot-Files/String which I would like to render in the UI

**Describe the solution you'd like**
Support for rendering Graphviz dot-strings / AST in React

**Describe alternatives you've considered**
I have not yet found any and am open to be directed to existing alternatives

**Additional context**
N/A

**Comment by kamiazya** [comment]
@its-felix 
Thank you for raising this feature request! We understand your need to render Graphviz dot-strings or AST within a React UI visually.

Our library doesn't directly support rendering these in-browser using SVG or similar formats. However, it's possible to achieve identical functionality by integrating our library with other existing ones.

You might find the implementation in the following repository helpful as a reference: [react-dom-graphviz-integration](https://github.com/ts-graphviz/react-dom-graphviz-integration).

**Comment by its-felix** [comment]
Thanks for the suggestion!
Over the weekend, I have experimented with both https://reactflow.dev/ and https://github.com/uber/react-digraph with some logic to convert the graph AST to a graph representation for each of these libraries, which worked good enough.
