### ISSUE TITLE
parse does not parse escape codes, but stringify escapes backslashes

### ISSUE THREAD

**Issue by haved** [ts-graphviz/ts-graphviz#1202]
## Describe the bug

Round-tripping a graph through `parse` and `stringify` ends up turning all literal `\n` into `\\n`.

## To Reproduce

```typescript
const inputGraph = `\
digraph {
  a [
    label="Hello\\nWorld!";
  ];
}`;
console.log(inputGraph);
const ast = parse(inputGraph);
const outputGraph = stringify(ast);
console.log(outputGraph);
```

## Expected behavior

I expect the two `console.log` statements to print the same dot code (ignoring whitespace).
Instead, what is printed to the console is the following:

```
digraph {
  a [
    label="Hello\nWorld!";
  ];
}
digraph {
  a [
    label = "Hello\\nWorld!";
  ];
}
```

## Additional context

Internally, the AST stores the attribute value as separate backslash and n characters. Then `stringify` escapes the backslash character. This can be fixed in two ways: either `parse` turns `\n` in the dot source into a newline character in the AST's string, or `stringify` stops escaping.

A workaround is to replace all `\\` in the output of stingify with a single `\`.

Thank you for the library, by the way!

**Comment by kamiazya** [comment]
Hi, @haved 

Thank you for reporting this issue and providing a detailed explanation along with steps to reproduce it. We appreciate your feedback and are glad to hear that you're finding the library useful.

We've investigated the problem you've described regarding the inconsistent handling of escape sequences when parsing and stringifying DOT graphs—specifically, the issue where a literal `\n` turns into `\\n` after round-tripping through `parse` and `stringify`.

To address this, we've created PR #1204, which introduces a new `escape` function to correctly handle string escaping in the DOT language. This fix ensures that characters like `\n`, `\r`, and `\"` are properly managed, preserving the intended formatting of your graphs.

The PR is currently under review, and we expect to release it soon. We believe this update will resolve the inconsistencies you've encountered.

Your detailed report was instrumental in identifying and fixing this issue. Once again, thank you for your valuable contribution to improving the library. If you have any further questions or run into any other issues, please don't hesitate to let us know.

Best regards,

kamiazya

**Comment by nagasawaryoya** [comment]
@all-contributors please add @haved for bug
