### ISSUE TITLE
Unable to use rank attribute for subgraph

### ISSUE THREAD

**Issue by mimiz** [ts-graphviz/ts-graphviz#334]
## Describe the bug

First, thank you for this project, it fits most of my needs, only I think it's not possible to use the rank attribute... 
See the simple example : 

## To Reproduce

```typescript
import { attribute, Digraph, digraph, toDot, } from 'ts-graphviz';

const graph = digraph('demo');
const A = graph.createNode('A')
const B = graph.createNode('B')
const C = graph.createNode('C')

graph.createEdge([A, B, C]);

graph.createSubgraph("", { rank: "same;A,C" })

const dot = toDot(graph);

console.log(dot);
```

this will generate : 

```dot
digraph "demo" {
  "A";
  "B";
  "C";
  subgraph {
    rank = "same;A,C";
  }
  "A" -> "B" -> "C";
}
```

This will create the image:  https://imgur.com/amt18gA

## Expected behavior

I would like to have an image like this, 

The way to do it is: https://imgur.com/Q0tRTIk

```dot
digraph "demo" {
  "A";
  "B";
  "C";
  subgraph {
    rank = "same"; "A"; "C";
  }
  "A" -> "B" -> "C";
}
```
## Additional context

I will try to have a look at the source code to see if I am able to make a PR. 
Or if there is a way to create the rank in a good way, maybe a little add to the Reame will be perfect.

Regards

**Comment by mimiz** [comment]
Hi, 
My bad I was able to create what I want like this : 

```typescript

import { digraph, toDot, } from 'ts-graphviz';

const graph = digraph('demo');

const B = graph.createNode('B')
const sub = graph.createSubgraph('undefined', { rank: "same" })
const A = sub.createNode('A')
const C = sub.createNode('C')
graph.createEdge([A, B, C]);

const dot = toDot(graph);

console.log(dot);
```

Sorry for reporting a bug

**Comment by mimiz** [comment]
I thought I found a way to get where I want, but I couldn't ...
We should be able to something like this : https://stackoverflow.com/questions/25734244/how-do-i-place-nodes-on-the-same-level-in-dot

**Comment by kamiazya** [comment]
@mimiz 
Thank you for the question.

My understanding is that you don't even write the node name on the same line as the rank attribute, so you can do something like this:

https://runkit.com/kamiazya/use-rank-attribute-for-subgraph

Can this solve your problem?

**Comment by kamiazya** [comment]
Since there is no reaction, close it.
Please open it if necessary.

Or ask a question in Discussions.
