### ISSUE TITLE
Consider typing the attributes

### ISSUE THREAD

**Issue by dustinlacewell** [ts-graphviz/ts-graphviz#542]
It'd be pretty nifty if there were types provided for the various attributes. Bonus if they are polymorphic based on what engine is being utilized.

**Comment by kamiazya** [comment]
@dustinlacewell 
Sounds good!

I remember giving up because I couldn't make a concrete design.

We are looking for ideas and PR.

**Comment by kamiazya** [comment]
@dustinlacewell I tried to define the type, but I'm not sure if it's the type definition I intended.

I've committed a build of #551  to the attribute-types-demo branch, can you please review it?

```bash
yarn add 'ts-graphviz/ts-graphviz#attribute-types-demo'
```

I would be grateful if other people could give us their opinions.

**Comment by kamiazya** [comment]
After considering compatibility, maintainability, etc., we'll get feedback on this in the near future with a release.

**Comment by kamiazya** [comment]
It was merged into the v1 branch, but it was decided to reconsider the development plan, so it was reopened.
