### ISSUE TITLE
`class` missing from attribute types

### ISSUE THREAD

**Issue by blake-regalia** [ts-graphviz/ts-graphviz#789]
## Describe the bug

This bug report actually comprises of two closely related issues.

1. Using the `_class` key in an attribute struct, which I presume was done to avoid conflict with the reserved keyword in JS, produces a literal `_class` attribute in the output DOT, which is incorrect.

2. The `class` type string is missing from the attribute type unions, but i think (maybe the developer intentions are different) that it should be there for when users pass attributes in as a struct (i.e., via the declarative API).

## To Reproduce

```typescript
console.log(toDot(digraph('g', g => {
   g.node('n', {
      _class: 'custom-class',
      // --- or even ---
      [attribute._class]: 'custom-class',
   });
})));
```

❌ produces dot with a useless `_class` attribute:
```dot
digraph "g" {
  "n" [
    _class = "custom-class";
  ];
}
```

If we use the `class` key directly, it produces the correct results, but the type system rejects the attribute struct since `class` is not a member of the `NodeAttributeKey` type union
```typescript
console.log(toDot(digraph('g', g => {
   g.node('n', {
      class: 'custom-class',
   });
})));
```

✅ correct:
```dot
digraph "g" {
  "n" [
    class = "custom-class";
  ];
}
```

**Comment by kamiazya** [comment]
Hi @blake-regalia ,

It is indeed possible that `_class` was used during development to avoid the JavaScript class keyword.

However, when I tested it at hand, the problem did not occur even when `class` was specified, so it is most likely just a bug.

Thanks for reporting.

**Comment by kamiazya** [comment]
@all-contributors please add @blake-regalia  for bug.
