### ISSUE TITLE
V1 Migration guide

### ISSUE THREAD

**Issue by trevor-scheer** [ts-graphviz/ts-graphviz#819]
Hey there! I've recently re-become a maintainer on the [apollographql/federation](https://github.com/apollographql/federation) repo. We've got an open renovate PR to upgrade our usage of your package to v1, but the migration path is non-obvious to me in the release notes. It looks like a number of types have changed or been removed (which the release notes do call out) but the path forward is non-obvious for some of them (like `ICluster`, for example).

Our entire usage of `ts-graphviz` exists in [this file](https://github.com/apollographql/federation/blob/main/query-graphs-js/src/graphviz.ts).

I did take a look at [the PR which implements the breaking changes](https://github.com/ts-graphviz/ts-graphviz/pull/651) and it's massive.

Any help would be appreciated!

**Comment by kamiazya** [comment]
@trevor-scheer 
Hi!

v1 is rough as far as documentation is concerned due to significant changes in the internal structure.
I apologize for the inconvenience.

The migration from apollographql/federation to ts-graphviz@v1 can probably be done with fewer changes.
Once I have added the necessary information to PR #651, I will contact you again.

Thanks!

**Comment by trevor-scheer** [comment]
Sounds good, thanks for the quick response!

**Comment by kamiazya** [comment]
@trevor-scheer 
I have updated the PR and Release Notes documentation with information regarding the apollographql/federation project update.

- https://github.com/ts-graphviz/ts-graphviz/pull/651
- https://github.com/ts-graphviz/ts-graphviz/releases/tag/v1.0.0

Please see the `Interface Naming Conventions' section.

I have also created a PR for the code generated during the verification process.

I am just doing the migration and want you to verify that it works.

https://github.com/apollographql/federation/pull/2395

Thanks!

**Comment by kamiazya** [comment]
The issue will be pinned so that anyone can ask questions if they have any issues regarding the transition to v1.

If you have questions, please comment and re-open.
